# Generated by Django 4.2.2 on 2023-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='name', max_length=120),
        ),
    ]
