# Generated by Django 4.2.2 on 2023-06-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0002_salesperson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='name',
        ),
    ]
