# Generated by Django 4.2.2 on 2023-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0003_remove_salesperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='salespersons'),
        ),
    ]
